// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1jaZQ5VNTq-sAhbLDygPweCDTvzfp2M',
    appId: '1:826157456247:web:12447f658970d77cc19f72',
    messagingSenderId: '826157456247',
    projectId: 'ecommercapp-ccd91',
    authDomain: 'ecommercapp-ccd91.firebaseapp.com',
    databaseURL: 'https://ecommercapp-ccd91-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercapp-ccd91.appspot.com',
    measurementId: 'G-SFVQ3Y75RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF83Uo_lhS8hKB9CCB3e8PZlAuVq9C_00',
    appId: '1:826157456247:android:f96cebbc817f0281c19f72',
    messagingSenderId: '826157456247',
    projectId: 'ecommercapp-ccd91',
    databaseURL: 'https://ecommercapp-ccd91-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercapp-ccd91.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0nnuWlPkUMGzdZ94VyAsyoK52Znko0XY',
    appId: '1:826157456247:ios:0a8890432c7ad3acc19f72',
    messagingSenderId: '826157456247',
    projectId: 'ecommercapp-ccd91',
    databaseURL: 'https://ecommercapp-ccd91-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercapp-ccd91.appspot.com',
    androidClientId: '826157456247-rmccns5cn37bo01fkqmu8p87h1rnrqj3.apps.googleusercontent.com',
    iosClientId: '826157456247-a14tjsna73n12s1fqfumt9ukis93ms90.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercecoursenmmm',
  );
}
